### ISSUE TITLE
Term Distributer Definition Edit

### ISSUE THREAD

**Issue by TristanJoslinBCGov** [bcgov/data-publication#50]
Currently in the GLOSSARY at this address:  
https://bcgov.github.io/data-publication/pages/glossary.html
the **Term** Distributer has a **Definition** of:
"A_Role_ in the BC Data Catalogue, the Distributor is someone who:"

To find all the roles in the catalogue in that list I searched on:
"Role in the BC Data Catalogue", but the Distributer role was not found because of the underlines.
I assume there needs to be a space between the "A" and the first underscore and that the underscores allow italicizing the word "Role".

**Comment by mdunhamwilkie** [comment]
Thanks @TristanJoslinBCGov  - I've fixed this
